/**
 * Cross-division, multi-language sample packs — SEED CONTENT ONLY.
 *
 * Demonstrates the group shape: one product per division, each with its own
 * advisor type and claim regime, plus market-approved language packs so the
 * language layer can be tested end to end. Replace every line with
 * brand-approved copy during Brand Enablement.
 */

import type { LaunchPack, Product } from "./types";
import type { TranslationStatus } from "./languages";

export interface SeedProduct extends Product {
  brandId: string;
  divisionId: string;
}

export const CATALOGUE: SeedProduct[] = [
  {
    id: "lrp-effaclar-duo", brandId: "la-roche-posay", divisionId: "derm",
    brand: "La Roche-Posay", category: "skincare",
    name: "Effaclar Duo+M Anti-Imperfection Care",
    tagline: "Corrects and unclogs — for blemish-prone skin",
    launchLabel: "Priority Launch",
  },
  {
    id: "lancome-genifique", brandId: "lancome", divisionId: "luxe",
    brand: "Lancôme", category: "skincare",
    name: "Advanced Génifique Radiance Serum",
    tagline: "Skin looks visibly radiant in 7 days",
    launchLabel: "Priority Launch",
  },
  {
    id: "kerastase-gloss-absolu", brandId: "kerastase", divisionId: "ppd",
    brand: "Kérastase", category: "haircare",
    name: "Gloss Absolu Shine Gloss Service",
    tagline: "Salon gloss service — mirror shine for 6 weeks",
    launchLabel: "Priority Launch",
  },
  {
    id: "maybelline-sky-high", brandId: "maybelline", divisionId: "cpd",
    brand: "Maybelline New York", category: "makeup",
    name: "Lash Sensational Sky High Mascara",
    tagline: "Limitless length, no clumps",
    launchLabel: null,
  },
];

type PackBody = Omit<LaunchPack, "id" | "version" | "productId">;

/** productId -> language -> pack body (+ governance status). */
export const CATALOGUE_PACKS: Record<
  string,
  Record<string, PackBody & { status: TranslationStatus }>
> = {
  "lrp-effaclar-duo": {
    EN: {
      language: "EN", status: "source",
      sections: [
        { id: "positioning", title: "Positioning",
          content: "Effaclar Duo+M is the dermatological reference for blemish-prone skin. The one-line message: corrects imperfections and unclogs pores, while helping limit marks from coming back. Position it as pharmacy-grade correction, not a cosmetic quick fix.",
          keywords: ["positioning","message","story","about","what is","introduce"] },
        { id: "claims", title: "Hero claims (approved wording)",
          content: "Approved claims: formulated with niacinamide and salicylic acid. Visibly corrects imperfections. Helps unclog pores. Helps limit the reappearance of marks. Tested on sensitive, blemish-prone skin under dermatological control. Non-comedogenic.",
          keywords: ["claim","results","proof","works","evidence","niacinamide","salicylic"] },
        { id: "ingredients", title: "Ingredient story",
          content: "Salicylic acid gently exfoliates and helps unclog pores; niacinamide helps soothe visible redness; the formula is built on La Roche-Posay Thermal Spring Water for tolerance on sensitive skin.",
          keywords: ["ingredient","formula","inside","contains","active"] },
        { id: "routine", title: "Routine placement",
          content: "Apply morning and evening to cleansed skin, on the whole face rather than as a spot treatment. Layer under sunscreen in the morning — exfoliating actives make daily SPF essential.",
          keywords: ["routine","apply","use","when","how","steps","morning","night"] },
        { id: "price", title: "Price positioning",
          content: "Pharmacy positioning: a dermatologist-recommended formula at a fraction of a prescription course, and a single tube typically lasts two months at twice-daily use.",
          keywords: ["price","cost","expensive","value","compare"] },
        { id: "upsell", title: "Complete the routine",
          content: "Pair with Effaclar Foaming Gel cleanser and Anthelios UVMune SPF50+ Fluid. The routine is what delivers results — cleanse, correct, protect.",
          keywords: ["upsell","companion","also","together","recommend","pair"] },
      ],
      objections: [
        { objection: "It's too strong for my sensitive skin.",
          keywords: ["strong","sensitive","irritate","harsh","react","burn"],
          approvedResponse: "This formula was tested on sensitive, blemish-prone skin under dermatological control and is non-comedogenic. Start once daily in the evening for the first week, then build to twice daily as tolerance allows." },
        { objection: "I can buy a cheaper acne cream.",
          keywords: ["cheaper","price","expensive","cost","pharmacy","brand"],
          approvedResponse: "The difference is tolerance and testing. This combines salicylic acid with niacinamide on a thermal spring water base, tested under dermatological control — which matters when skin is already reactive." },
      ],
      doNotSay: ["cures acne","medical treatment","prescription strength","guaranteed results","clears skin permanently"],
      approvedClaims: ["niacinamide and salicylic acid","visibly corrects imperfections","helps unclog pores","helps limit the reappearance of marks","under dermatological control","non-comedogenic"],
    },
    FR: {
      language: "FR", status: "approved",
      sections: [
        { id: "positioning", title: "Positionnement",
          content: "Effaclar Duo+M est la référence dermatologique pour les peaux à imperfections. Le message clé : corrige les imperfections et désobstrue les pores, tout en aidant à limiter la réapparition des marques. À positionner comme une correction de qualité pharmacie, non comme un geste cosmétique ponctuel.",
          keywords: ["positionnement","message","présenter","qu'est-ce","introduire"] },
        { id: "claims", title: "Allégations approuvées",
          content: "Allégations approuvées : formulé avec de la niacinamide et de l'acide salicylique. Corrige visiblement les imperfections. Aide à désobstruer les pores. Aide à limiter la réapparition des marques. Testé sous contrôle dermatologique sur peaux sensibles à imperfections. Non comédogène.",
          keywords: ["allégation","preuve","résultat","efficace","niacinamide","salicylique"] },
        { id: "routine", title: "Place dans la routine",
          content: "Appliquer matin et soir sur peau nettoyée, sur l'ensemble du visage plutôt qu'en traitement local. Superposer sous une protection solaire le matin : les actifs exfoliants rendent le SPF quotidien indispensable.",
          keywords: ["routine","appliquer","utiliser","quand","comment","matin","soir"] },
        { id: "price", title: "Positionnement prix",
          content: "Positionnement pharmacie : une formule recommandée par les dermatologues, et un tube dure généralement deux mois à raison de deux applications par jour.",
          keywords: ["prix","coût","cher","valeur","comparer"] },
      ],
      objections: [
        { objection: "C'est trop fort pour ma peau sensible.",
          keywords: ["fort","sensible","irrite","agressif","réaction"],
          approvedResponse: "Cette formule est testée sous contrôle dermatologique sur peaux sensibles à imperfections et elle est non comédogène. Commencez une fois par jour le soir la première semaine, puis passez à deux fois par jour selon la tolérance." },
      ],
      doNotSay: ["guérit l'acné","traitement médical","résultats garantis"],
      approvedClaims: ["niacinamide et acide salicylique","corrige visiblement les imperfections","aide à désobstruer les pores","sous contrôle dermatologique","non comédogène"],
    },
    AR: {
      language: "AR", status: "approved",
      sections: [
        { id: "positioning", title: "التموضع",
          content: "إيفاكلار ديو+ إم هو المرجع الطبي للبشرة المعرضة للعيوب. الرسالة الأساسية: يصحح العيوب ويساعد على فتح المسام، ويحد من عودة الآثار. قدّميه كعلاج تصحيحي من الصيدلية وليس كمستحضر تجميلي سريع.",
          keywords: ["تموضع","رسالة","تعريف","ما هو","المنتج"] },
        { id: "claims", title: "الادعاءات المعتمدة",
          content: "الادعاءات المعتمدة: يحتوي على النياسيناميد وحمض الساليسيليك. يصحح العيوب بشكل مرئي. يساعد على فتح المسام. يساعد على الحد من عودة الآثار. تم اختباره تحت إشراف طبي على البشرة الحساسة. لا يسد المسام.",
          keywords: ["ادعاء","نتائج","فعالية","نياسيناميد","ساليسيليك"] },
        { id: "routine", title: "مكانه في الروتين",
          content: "يُستخدم صباحاً ومساءً على بشرة نظيفة، على الوجه كاملاً وليس كعلاج موضعي. ضعي واقي الشمس فوقه في الصباح — فالمكونات المقشّرة تجعل الحماية اليومية ضرورية.",
          keywords: ["روتين","استخدام","كيف","متى","صباح","مساء"] },
      ],
      objections: [
        { objection: "هذا المنتج قوي جداً على بشرتي الحساسة.",
          keywords: ["قوي","حساسة","تهيج","حرقان"],
          approvedResponse: "تم اختبار هذه التركيبة تحت إشراف طبي على البشرة الحساسة المعرضة للعيوب، وهي لا تسد المسام. ابدئي بمرة واحدة مساءً في الأسبوع الأول، ثم مرتين يومياً حسب التحمل." },
      ],
      doNotSay: ["يعالج حب الشباب","علاج طبي","نتائج مضمونة"],
      approvedClaims: ["النياسيناميد وحمض الساليسيليك","يصحح العيوب بشكل مرئي","يساعد على فتح المسام","تحت إشراف طبي"],
    },
    ZH: {
      language: "ZH", status: "approved",
      sections: [
        { id: "positioning", title: "产品定位",
          content: "药房定位：皮肤科推荐的日常护理，适合易长瑕疵的肌肤。它可见改善瑕疵并帮助减少反复——它是化妆品护理，不是药品。",
          keywords: ["定位","介绍","是什么","产品","讲讲"] },
        { id: "claims", title: "核心宣称",
          content: "认可宣称：含烟酰胺与水杨酸。可见改善瑕疵。帮助疏通毛孔。帮助减少痘印反复。经敏感肌皮肤科监测测试。不致痘。",
          keywords: ["宣称","功效","效果","烟酰胺","水杨酸","证据"] },
        { id: "routine", title: "使用流程",
          content: "早晚洁面后在干爽肌肤上使用，用于特安洁面啫喱之后。早晨务必搭配不致痘的防晒——水杨酸会增加光敏感。",
          keywords: ["流程","怎么用","使用","什么时候","洁面","早晚"] },
        { id: "price", title: "价格定位",
          content: "药房定位：皮肤科推荐的配方，一支按每日两次使用通常可用两个月。",
          keywords: ["价格","多少钱","价值","贵","对比"] },
      ],
      objections: [
        { objection: "这个能治好我的痘痘吗？",
          keywords: ["痘","痤疮","治好","治疗","药","处方"],
          approvedResponse: "这是一款化妆品护理，可见改善瑕疵并帮助减少反复。如果是需要治疗的痤疮，正确的做法是看皮肤科医生或咨询药师——这款产品可以配合他们的建议一起使用。" },
        { objection: "太贵了",
          keywords: ["贵","价格","多少钱","便宜"],
          approvedResponse: "我理解。这是皮肤科推荐的配方，并经敏感肌皮肤科监测测试，一支按每日两次使用通常可用两个月。" },
      ],
      doNotSay: ["治疗痤疮","治愈痘痘","医疗级","可以代替处方药"],
      approvedClaims: ["含烟酰胺与水杨酸","可见改善瑕疵","帮助疏通毛孔","帮助减少痘印反复","经敏感肌皮肤科监测测试","不致痘"],
    },
    JA: {
      language: "JA", status: "approved",
      sections: [
        { id: "positioning", title: "ポジショニング",
          content: "薬局でのポジション：皮膚科医が推奨する、気になりやすい肌のための毎日のお手入れです。気になる部分を目立ちにくくし、繰り返しにアプローチします——化粧品であり、医薬品ではありません。",
          keywords: ["紹介","メッセージ","どんな","製品","説明"] },
        { id: "claims", title: "承認訴求",
          content: "承認訴求：ナイアシンアミドとサリチル酸配合。肌の気になる部分を目立ちにくくします。毛穴の詰まりにアプローチします。繰り返しにくい肌へ。敏感肌で皮膚科医監修のもとテスト済み。ノンコメドジェニックテスト済み。",
          keywords: ["訴求","効果","結果","ナイアシンアミド","サリチル酸","証拠"] },
        { id: "routine", title: "使用手順",
          content: "エファクラ クレンジングジェルのあと、清潔で乾いた肌に朝晩お使いください。朝はノンコメドジェニックの日やけ止めを必ず併用してください——サリチル酸は紫外線への感受性を高めます。",
          keywords: ["手順","使い方","いつ","洗顔","朝","夜"] },
        { id: "price", title: "価格ポジション",
          content: "薬局でのポジション：皮膚科医が推奨する処方で、1日2回の使用で1本およそ2か月お使いいただけます。",
          keywords: ["価格","値段","高い","価値","比較"] },
      ],
      objections: [
        { objection: "これでニキビは治りますか",
          keywords: ["ニキビ","治る","治療","薬","処方"],
          approvedResponse: "こちらは化粧品で、気になる部分を目立ちにくくし、繰り返しにアプローチするお手入れです。治療が必要なニキビについては、皮膚科の受診または薬剤師へのご相談が正しい一歩です。そのうえで、このお手入れを併用いただけます。" },
        { objection: "高いですね",
          keywords: ["高い","値段","価格","予算"],
          approvedResponse: "ごもっともです。皮膚科医が推奨する処方で、敏感肌で皮膚科医監修のもとテスト済みです。1日2回の使用で1本およそ2か月お使いいただけます。" },
      ],
      doNotSay: ["ニキビを治療する","肌荒れを治す","医療グレード","処方薬の代わりになる"],
      approvedClaims: ["ナイアシンアミドとサリチル酸配合","肌の気になる部分を目立ちにくく","毛穴の詰まりにアプローチ","繰り返しにくい肌へ","敏感肌で皮膚科医監修のもとテスト済み","ノンコメドジェニックテスト済み"],
    },
    HI: {
      language: "HI", status: "approved",
      sections: [
        { id: "positioning", title: "पोज़िशनिंग",
          content: "फ़ार्मेसी पोज़िशनिंग: धब्बों की संभावना वाली त्वचा के लिए डर्मेटोलॉजिस्ट द्वारा सुझाई गई रोज़ाना की देखभाल। यह दिखने वाले धब्बे कम करता है और उनकी वापसी सीमित करने में मदद करता है — यह कॉस्मेटिक केयर है, दवा नहीं।",
          keywords: ["पोज़िशन","बताइए","क्या है","प्रोडक्ट","परिचय"] },
        { id: "claims", title: "मुख्य दावे",
          content: "स्वीकृत दावे: नियासिनामाइड और सैलिसिलिक एसिड युक्त। दिखने में धब्बे कम करता है। रोमछिद्र खोलने में मदद करता है। निशानों की वापसी सीमित करने में मदद करता है। संवेदनशील त्वचा पर डर्मेटोलॉजिकल निगरानी में परीक्षित। नॉन-कॉमेडोजेनिक।",
          keywords: ["दावा","नतीजे","नियासिनामाइड","सैलिसिलिक","सबूत"] },
        { id: "routine", title: "रूटीन में जगह",
          content: "एफ़ाक्लार जेल क्लेंज़र के बाद साफ़, सूखी त्वचा पर सुबह और रात लगाएँ। सुबह हमेशा नॉन-कॉमेडोजेनिक सनस्क्रीन के साथ इस्तेमाल करें — सैलिसिलिक एसिड धूप के प्रति संवेदनशीलता बढ़ाता है।",
          keywords: ["रूटीन","कैसे","इस्तेमाल","कब","क्लेंज़र","सुबह","रात"] },
        { id: "price", title: "कीमत की स्थिति",
          content: "फ़ार्मेसी पोज़िशनिंग: डर्मेटोलॉजिस्ट द्वारा सुझाया गया फ़ॉर्मूला, और दिन में दो बार इस्तेमाल पर एक ट्यूब आमतौर पर दो महीने चलती है।",
          keywords: ["कीमत","दाम","वैल्यू","महंगा","तुलना"] },
      ],
      objections: [
        { objection: "क्या इससे मुँहासे ठीक होंगे?",
          keywords: ["मुँहासे","पिंपल","ठीक","इलाज","दवा"],
          approvedResponse: "यह एक कॉस्मेटिक केयर है जो दिखने वाले धब्बे कम करती है और उनकी वापसी सीमित करने में मदद करती है। जिस मुँहासे को इलाज चाहिए, उसके लिए सही कदम है डर्मेटोलॉजिस्ट से मिलना या फ़ार्मासिस्ट से बात करना — यह उनके सुझाव के साथ इस्तेमाल हो सकता है।" },
        { objection: "बहुत महंगा है",
          keywords: ["महंगा","कीमत","दाम","सस्ता"],
          approvedResponse: "समझती हूँ। यह डर्मेटोलॉजिस्ट द्वारा सुझाया गया फ़ॉर्मूला है, संवेदनशील त्वचा पर डर्मेटोलॉजिकल निगरानी में परीक्षित, और दिन में दो बार इस्तेमाल पर एक ट्यूब लगभग दो महीने चलती है।" },
      ],
      doNotSay: ["मुँहासे का इलाज करता है","पिंपल ठीक करता है","मेडिकल ग्रेड","आपकी दवा की जगह लेता है"],
      approvedClaims: ["नियासिनामाइड और सैलिसिलिक एसिड युक्त","दिखने में धब्बे कम करता है","रोमछिद्र खोलने में मदद","निशानों की वापसी सीमित करने में मदद","संवेदनशील त्वचा पर डर्मेटोलॉजिकल निगरानी में परीक्षित","नॉन-कॉमेडोजेनिक"],
    },
  },

  "lancome-genifique": {
    EN: {
      language: "EN", status: "source",
      sections: [
        { id: "positioning", title: "Positioning",
          content: "Advanced Génifique is Lancôme's icon of radiance and the entry point to the ritual. The one-line message: skin looks visibly radiant and feels stronger in seven days. Sell the ritual and the diagnosis, never the ingredient list alone.",
          keywords: ["positioning","message","story","about","what is","introduce"] },
        { id: "claims", title: "Hero claims (approved wording)",
          content: "Approved claims: powered by a probiotic-derived fractions and prebiotic complex. Skin looks visibly radiant in seven days. Skin feels stronger and more resilient. Suitable for all skin types and tones. Fragrance formulated for sensitive skin.",
          keywords: ["claim","results","proof","works","evidence","probiotic","radiance"] },
        { id: "ingredients", title: "Ingredient story",
          content: "A complex of probiotic-derived fractions and prebiotics supports the skin's natural barrier and microbiome balance, which is what drives the visible radiance result.",
          keywords: ["ingredient","formula","inside","contains","active","microbiome"] },
        { id: "routine", title: "Routine placement",
          content: "The first step after cleansing, morning and evening — seven drops, warmed between the palms and pressed into the skin. It preps skin so everything applied after performs better.",
          keywords: ["routine","apply","use","when","how","steps","morning","night","ritual"] },
        { id: "price", title: "Price positioning",
          content: "Luxury positioning justified by the ritual and the results timeline. Frame the conversation around the seven-day result and the size options rather than defending the price outright.",
          keywords: ["price","cost","expensive","value","compare","worth"] },
        { id: "upsell", title: "Complete the ritual",
          content: "Layer with Génifique Eye Cream and finish with Absolue or Rénergie moisturiser. Offer the ritual as a diagnosis-led routine, not a bundle.",
          keywords: ["upsell","companion","also","together","recommend","pair","ritual"] },
      ],
      objections: [
        { objection: "It's very expensive for a small bottle.",
          keywords: ["expensive","price","cost","small","afford","worth"],
          approvedResponse: "I understand. Seven drops is one application, so the 50ml lasts about three months — and it is the step that makes everything after it work harder. May I show you how it changes the feel of your skin right now?" },
        { objection: "I already have a serum I like.",
          keywords: ["already","have","serum","using","another","brand"],
          approvedResponse: "That's a great starting point. May I ask what result you want next — radiance, comfort or firmness? Génifique is a first-step serum, so it often layers under what you already use rather than replacing it." },
      ],
      doNotSay: ["anti-ageing cure","medical treatment","guaranteed results","erases wrinkles"],
      approvedClaims: ["probiotic-derived fractions","skin looks visibly radiant in seven days","skin feels stronger","all skin types and tones"],
    },
    ZH: {
      language: "ZH", status: "approved",
      sections: [
        { id: "positioning", title: "产品定位",
          content: "小黑瓶精华是兰蔻的光泽象征，也是整套护肤仪式的第一步。核心信息：七天后肌肤看起来明显焕发光泽，触感更强韧。销售的是仪式感与肌肤诊断，而不仅仅是成分表。",
          keywords: ["定位","信息","介绍","是什么","产品"] },
        { id: "claims", title: "官方认可宣称",
          content: "认可宣称：含益生菌衍生物与益生元复合成分。七天后肌肤看起来明显焕发光泽。肌肤触感更强韧。适合所有肤质与肤色。香氛专为敏感肌配方设计。",
          keywords: ["宣称","效果","功效","证明","益生菌","光泽"] },
        { id: "routine", title: "使用步骤",
          content: "洁面后的第一步，早晚各一次——取七滴于掌心温热后按压于肌肤。它为后续护肤品打底，让后续产品效果更好。",
          keywords: ["步骤","使用","怎么用","何时","早晚","仪式"] },
        { id: "price", title: "价格沟通",
          content: "奢华定位源于仪式感与七天见效的时间承诺。请围绕七天效果与规格选择展开对话，而不是直接为价格辩护。",
          keywords: ["价格","贵","价值","比较","值得"] },
      ],
      objections: [
        { objection: "这么小一瓶太贵了。",
          keywords: ["贵","价格","小","划算","值得"],
          approvedResponse: "我理解您的顾虑。每次七滴，50毫升大约可以使用三个月，而且它是让后续所有产品发挥更好效果的关键一步。我可以现在为您试用，让您感受一下肌肤的变化吗？" },
      ],
      doNotSay: ["抗衰老治疗","医疗功效","保证效果","去除皱纹"],
      approvedClaims: ["益生菌衍生物","七天后肌肤看起来明显焕发光泽","肌肤触感更强韧","适合所有肤质"],
    },
    JA: {
      language: "JA", status: "approved",
      sections: [
        { id: "positioning", title: "ポジショニング",
          content: "ジェニフィックはランコムの輝きの象徴であり、スキンケア儀式の第一歩です。キーメッセージ：7日間で肌が見た目に輝き、より健やかな手触りに。成分の羅列ではなく、儀式とカウンセリングを提案してください。",
          keywords: ["ポジショニング","メッセージ","紹介","とは","商品"] },
        { id: "claims", title: "承認されたクレーム",
          content: "承認クレーム：プロバイオティクス由来成分とプレバイオティクス複合体を配合。7日間で肌が見た目に輝きます。肌がより健やかな手触りに。すべての肌質・肌色に。敏感肌にも配慮した香料設計。",
          keywords: ["クレーム","効果","結果","証明","プロバイオティクス","輝き"] },
        { id: "routine", title: "使用手順",
          content: "洗顔後の最初のステップとして、朝晩に7滴を手のひらで温めてから肌に押し込むようになじませます。後に使う製品の効果を高めます。",
          keywords: ["手順","使い方","いつ","朝","夜","儀式"] },
        { id: "price", title: "価格の伝え方",
          content: "価格ではなく、7日間の結果とサイズ展開を軸に会話を進めてください。7滴で1回分のため、50mlは約3か月お使いいただけます。",
          keywords: ["価格","高い","価値","比較"] },
      ],
      objections: [
        { objection: "小さいボトルなのに高いですね。",
          keywords: ["高い","価格","小さい","値段"],
          approvedResponse: "ごもっともです。1回7滴ですので、50mlで約3か月お使いいただけます。そして後に重ねる製品の効果を高める一歩でもあります。よろしければ今、お肌で感触をお試しいただけますか。" },
      ],
      doNotSay: ["アンチエイジング治療","医薬的効果","効果を保証","シワを消す"],
      approvedClaims: ["プロバイオティクス由来成分","7日間で肌が見た目に輝き","肌がより健やかな手触り","すべての肌質"],
    },
    FR: {
      language: "FR", status: "approved",
      sections: [
        { id: "positioning", title: "Positionnement",
          content: "Le rituel Luxe : Génifique est la première étape après le nettoyage, celle qui fait mieux travailler tout ce qui suit. Entrez par le rituel et la sensorialité, jamais par la remise.",
          keywords: ["positionnement","message","présenter","c'est quoi","produit","parlez"] },
        { id: "claims", title: "Allégations approuvées",
          content: "Formulé avec des fractions dérivées de probiotiques. La barrière cutanée paraît renforcée ; la peau est visiblement plus éclatante et le teint plus unifié. Convient à tous les types de peau.",
          keywords: ["allégation","résultats","preuve","probiotique","éclat","efficace"] },
        { id: "routine", title: "Place dans la routine",
          content: "Sept gouttes matin et soir sur peau nettoyée, avant tout autre soin. Déposez au compte-gouttes dans la paume, réchauffez brièvement, puis pressez sur la peau — le geste fait partie du rituel.",
          keywords: ["routine","appliquer","utiliser","comment","gouttes","étapes"] },
        { id: "price", title: "Positionnement prix",
          content: "Sept gouttes par application : un flacon de 50 ml dure environ trois mois. Présentez-le comme l'étape qui fait mieux travailler toute sa routine, pas comme une dépense supplémentaire.",
          keywords: ["prix","coût","valeur","cher","comparer"] },
      ],
      objections: [
        { objection: " C'est cher ",
          keywords: ["cher","prix","coût","budget"],
          approvedResponse: "Je comprends. Ce sont sept gouttes par utilisation, donc un flacon de 50 ml dure environ trois mois — et c'est l'étape qui aide tout ce que vous appliquez ensuite à mieux agir. Puis-je vous le faire ressentir sur la peau maintenant ?" },
        { objection: " J'utilise déjà un sérum ",
          keywords: ["déjà","autre","sérum","besoin","pourquoi"],
          approvedResponse: "Génifique se place avant votre sérum actuel plutôt que de le remplacer — c'est l'étape de préparation qui aide la suite à pénétrer et à agir. Essayons-le sur une moitié du visage pour que vous puissiez comparer ?" },
      ],
      doNotSay: ["répare l'ADN","cure anti-âge","cliniquement prouvé pour inverser"],
      approvedClaims: ["fractions dérivées de probiotiques","la barrière cutanée paraît renforcée","visiblement plus éclatante","teint plus unifié","convient à tous les types de peau","7 gouttes par application"],
    },
    AR: {
      language: "AR", status: "approved",
      sections: [
        { id: "positioning", title: "الموضع التسويقي",
          content: "طقس الفخامة: جينيفيك هو الخطوة الأولى بعد التنظيف، وهو ما يجعل كل منتج بعده يعمل بشكل أفضل. ابدئي من الطقس والإحساس، لا من الخصم.",
          keywords: ["تقديم","الرسالة","ما هو","عرّفي","المنتج"] },
        { id: "claims", title: "الادعاءات المعتمدة",
          content: "تركيبة بمكوّنات مشتقة من البروبيوتيك. حاجز البشرة يبدو أقوى، والبشرة تبدو أكثر إشراقاً وتوحّداً. مناسب لجميع أنواع البشرة.",
          keywords: ["ادعاء","نتائج","بروبيوتيك","إشراق","دليل"] },
        { id: "routine", title: "مكانه في الروتين",
          content: "سبع قطرات صباحاً ومساءً على بشرة نظيفة قبل أي عناية أخرى. ضعيها بالقطارة في راحة اليد، دفّئيها قليلاً، ثم اضغطيها على البشرة — الحركة نفسها جزء من الطقس.",
          keywords: ["روتين","استخدام","كيف","قطرات","خطوات"] },
        { id: "price", title: "موضع السعر",
          content: "سبع قطرات لكل استخدام تعني أن عبوة 50 مل تكفي حوالي ثلاثة أشهر. قدّميه كالخطوة التي تجعل بقية روتينها تعمل بشكل أفضل، لا كمصروف إضافي.",
          keywords: ["سعر","تكلفة","قيمة","غالي","مقارنة"] },
      ],
      objections: [
        { objection: "إنه غالٍ",
          keywords: ["غالي","سعر","تكلفة","كثير"],
          approvedResponse: "أتفهّم ذلك. سبع قطرات في كل استخدام، أي أن عبوة 50 مل تكفي حوالي ثلاثة أشهر — وهو الخطوة التي تساعد كل ما تضعينه بعده على العمل بشكل أفضل. هل أجرّبه لكِ على البشرة الآن؟" },
        { objection: "أستخدم سيروم بالفعل",
          keywords: ["بالفعل","سيروم","آخر","لماذا","أحتاج"],
          approvedResponse: "جينيفيك يأتي قبل السيروم الحالي ولا يحلّ محلّه — فهو خطوة التحضير التي تساعد ما يليه على الامتصاص والعمل. هل نجرّبه على نصف الوجه لتقارني بنفسكِ؟" },
      ],
      doNotSay: ["يصلح الحمض النووي","علاج لمكافحة الشيخوخة","مثبت سريرياً أنه يعكس"],
      approvedClaims: ["مكوّنات مشتقة من البروبيوتيك","حاجز البشرة يبدو أقوى","إشراق مرئي أكبر","لون بشرة أكثر توحّداً","مناسب لجميع أنواع البشرة","سبع قطرات في كل استخدام"],
    },
    HI: {
      language: "HI", status: "approved",
      sections: [
        { id: "positioning", title: "पोज़िशनिंग",
          content: "लक्ज़री रिचुअल: जेनिफ़िक क्लेंज़िंग के बाद पहला कदम है, जो उसके बाद लगने वाली हर चीज़ को बेहतर काम करने देता है। डिस्काउंट से नहीं, रिचुअल और अनुभव से शुरुआत करें।",
          keywords: ["पोज़िशन","बताइए","क्या है","प्रोडक्ट","परिचय"] },
        { id: "claims", title: "मुख्य दावे",
          content: "प्रोबायोटिक-व्युत्पन्न अंशों से बना। त्वचा की बैरियर मज़बूत महसूस होती है; त्वचा दिखने में अधिक निखरी और एकसमान लगती है। हर स्किन टाइप के लिए उपयुक्त।",
          keywords: ["दावा","नतीजे","प्रोबायोटिक","निखार","सबूत"] },
        { id: "routine", title: "रूटीन में जगह",
          content: "साफ़ त्वचा पर, किसी और ट्रीटमेंट से पहले, सुबह-शाम सात बूँदें। ड्रॉपर से हथेली पर लें, हल्का गर्म करें, फिर त्वचा पर दबाकर लगाएँ — यह क्रिया भी रिचुअल का हिस्सा है।",
          keywords: ["रूटीन","कैसे","इस्तेमाल","बूँद","स्टेप"] },
        { id: "price", title: "कीमत की स्थिति",
          content: "हर बार सात बूँदें, यानी 50ml की बोतल लगभग तीन महीने चलती है। इसे अतिरिक्त खर्च नहीं, बल्कि पूरे रूटीन को बेहतर बनाने वाला कदम बताएँ।",
          keywords: ["कीमत","दाम","महंगा","वैल्यू","तुलना"] },
      ],
      objections: [
        { objection: "यह महंगा है",
          keywords: ["महंगा","कीमत","दाम","बजट"],
          approvedResponse: "समझती हूँ। हर बार सात बूँदें, तो 50ml की बोतल लगभग तीन महीने चलती है — और यही वह कदम है जो बाद में लगने वाली हर चीज़ को बेहतर काम करने देता है। क्या मैं अभी आपकी त्वचा पर लगाकर दिखाऊँ?" },
        { objection: "मैं पहले से सीरम इस्तेमाल करती हूँ",
          keywords: ["पहले से","सीरम","ज़रूरत","क्यों","दूसरा"],
          approvedResponse: "जेनिफ़िक आपके मौजूदा सीरम की जगह नहीं लेता, उससे पहले आता है — यह तैयारी का कदम है जो आगे लगने वाली चीज़ों को बेहतर समाने और काम करने में मदद करता है। आधे चेहरे पर लगाकर तुलना कर लें?" },
      ],
      doNotSay: ["डीएनए ठीक करता है","एंटी-एजिंग इलाज","उलटने के लिए क्लिनिकली प्रमाणित"],
      approvedClaims: ["प्रोबायोटिक-व्युत्पन्न अंश","त्वचा की बैरियर मज़बूत महसूस होती है","दिखने में अधिक निखार","अधिक एकसमान रंगत","हर स्किन टाइप के लिए उपयुक्त","हर बार सात बूँदें"],
    },
  },

  "kerastase-gloss-absolu": {
    EN: {
      language: "EN", status: "source",
      sections: [
        { id: "positioning", title: "Positioning",
          content: "Gloss Absolu is an in-salon shine service, not a retail bottle. The one-line message to the client: mirror-like shine that lasts up to six weeks, with no change to hair colour. Position it as a bookable service that adds value to every colour appointment.",
          keywords: ["positioning","message","story","about","what is","introduce","service"] },
        { id: "claims", title: "Hero claims (approved wording)",
          content: "Approved claims: professional in-salon gloss service. Delivers mirror-like shine. Shine lasts up to six weeks. Can be used on natural or coloured hair. Seals the cuticle for smoother feel.",
          keywords: ["claim","results","proof","works","evidence","shine","weeks"] },
        { id: "routine", title: "Service protocol",
          content: "Apply to towel-dried, shampooed hair. Respect the mixing ratio and the processing time on the technical sheet, then rinse and finish. Sell the follow-up: the client rebooks the gloss with each colour service.",
          keywords: ["routine","apply","protocol","mixing","processing","time","how","steps"] },
        { id: "price", title: "Service pricing",
          content: "Priced as an add-on service to colour. The stylist's message is the six-week shine result and the rebooking rhythm — it raises the average ticket without extra chair time.",
          keywords: ["price","cost","ticket","charge","value","add-on"] },
        { id: "upsell", title: "Take-home recommendation",
          content: "Recommend the matching shine-maintenance shampoo and conditioner at the chair. Home care is what protects the six-week result the client is paying for.",
          keywords: ["upsell","companion","also","together","recommend","retail","home"] },
      ],
      objections: [
        { objection: "My client won't pay for an extra service.",
          keywords: ["pay","expensive","extra","cost","client","afford"],
          approvedResponse: "Frame it as protecting the colour they already paid for. The gloss adds shine for up to six weeks and brings them back on a rhythm — it raises the ticket without extra chair time." },
      ],
      doNotSay: ["permanent shine","changes hair colour","damage-free guarantee","lasts forever"],
      approvedClaims: ["professional in-salon gloss service","mirror-like shine","lasts up to six weeks","natural or coloured hair","seals the cuticle"],
    },
    FR: {
      language: "FR", status: "approved",
      sections: [
        { id: "positioning", title: "Positionnement",
          content: "C'est d'abord un service, ensuite un produit de revente. Positionnez-le au fauteuil : le rituel de brillance réalisé au bac, que la cliente prolonge ensuite à la maison.",
          keywords: ["positionnement","message","présenter","c'est quoi","produit","parlez"] },
        { id: "claims", title: "Allégations approuvées",
          content: "Le complexe de brillance glycolipidique scelle la cuticule et apporte une brillance miroir dès le premier service. Sans danger sur cheveux colorés.",
          keywords: ["allégation","résultats","preuve","brillance","efficace"] },
        { id: "routine", title: "Protocole de service",
          content: "Deux pressions des longueurs aux pointes sur cheveux essorés, émulsionner 30 secondes, laisser poser 3 minutes au bac, rincer. Ne pas appliquer aux racines — le poids à la racine donne un effet gras, pas brillant.",
          keywords: ["protocole","routine","appliquer","comment","service","pressions","bac"] },
        { id: "price", title: "Positionnement prix",
          content: "Valorisez le service, pas le flacon. Le produit à domicile prolonge le résultat salon entre deux rendez-vous — c'est la raison de l'emporter.",
          keywords: ["prix","coût","valeur","cher","comparer"] },
      ],
      objections: [
        { objection: " Ma cliente ne paiera pas un supplément ",
          keywords: ["cher","prix","coût","payer","supplément"],
          approvedResponse: "Ne le vendez pas comme un supplément — réalisez-le une fois au bac dans le service et laissez-la voir la brillance dans le miroir. La conversation revente vient après le résultat, pas avant." },
        { objection: " C'est comme un lissage kératine ? ",
          keywords: ["kératine","lissage","permanent","traitement"],
          approvedResponse: "Non — c'est un rituel de brillance qui scelle la cuticule, pas un service de lissage. Il apporte une brillance miroir dès le premier service et convient aux cheveux colorés." },
      ],
      doNotSay: ["brillance permanente","répare durablement le cheveu","équivalent à un lissage kératine"],
      approvedClaims: ["complexe de brillance glycolipidique","scelle la cuticule","apporte une brillance miroir dès le premier service","sans danger sur cheveux colorés","usage professionnel : 2 pressions des longueurs aux pointes"],
    },
    JA: {
      language: "JA", status: "approved",
      sections: [
        { id: "positioning", title: "ポジショニング",
          content: "まず施術、そのあとに店販です。チェアの上で位置づけてください：シャンプー台で行う艶のリチュアルを、お客様がご自宅で維持されます。",
          keywords: ["紹介","メッセージ","どんな","製品","説明"] },
        { id: "claims", title: "承認訴求",
          content: "グリコリピッド シャインコンプレックスがキューティクルを密着させ、初回の施術から鏡のような艶を与えます。カラー毛にもお使いいただけます。",
          keywords: ["訴求","効果","結果","艶","証拠"] },
        { id: "routine", title: "施術手順",
          content: "タオルドライ後、中間から毛先に2プッシュ。30秒乳化し、シャンプー台で3分置いてから流します。根元にはつけないでください——根元の重さは艶ではなくベタつきに見えます。",
          keywords: ["手順","使い方","施術","プッシュ","シャンプー台"] },
        { id: "price", title: "価格ポジション",
          content: "ボトルではなく施術に値付けしてください。ホームケアは次のご来店までサロンの仕上がりを保ちます——それが持ち帰る理由です。",
          keywords: ["価格","値段","高い","価値","比較"] },
      ],
      objections: [
        { objection: "追加メニューにはお金を出さないのでは",
          keywords: ["高い","値段","追加","メニュー","販売"],
          approvedResponse: "追加メニューとして売らないでください——施術の中でシャンプー台で一度行い、鏡で艶をご覧いただきます。店販のお話は結果をご覧いただいたあとで、前ではありません。" },
        { objection: "縮毛矯正と同じですか",
          keywords: ["縮毛","矯正","ストレート","永久","トリートメント"],
          approvedResponse: "いいえ——これはキューティクルを密着させる艶のリチュアルで、ストレートや矯正の施術ではありません。初回の施術から鏡のような艶を与え、カラー毛にもお使いいただけます。" },
      ],
      doNotSay: ["永久的な艶","髪を永久に修復する","縮毛矯正と同じ"],
      approvedClaims: ["グリコリピッド シャインコンプレックス","キューティクルを密着させます","初回の施術から鏡のような艶","カラー毛にもお使いいただけます","プロ用量：中間から毛先に2プッシュ"],
    },
    AR: {
      language: "AR", status: "approved",
      sections: [
        { id: "positioning", title: "الموضع التسويقي",
          content: "هذه خدمة أولاً ومنتج للبيع ثانياً. ضعيها في الكرسي: طقس اللمعان الذي تنفّذينه عند الحوض، ثم تحافظ عليه العميلة في المنزل.",
          keywords: ["تقديم","الرسالة","ما هو","عرّفي","المنتج"] },
        { id: "claims", title: "الادعاءات المعتمدة",
          content: "مركّب اللمعان الغليكوليبيدي يغلق طبقة الكيوتيكل ويمنح لمعاناً كالمرآة من الخدمة الأولى. آمن على الشعر المصبوغ.",
          keywords: ["ادعاء","نتائج","لمعان","دليل","فعالية"] },
        { id: "routine", title: "بروتوكول الخدمة",
          content: "ضغطتان من منتصف الطول إلى الأطراف على شعر منشّف بالمنشفة، استحلبي لمدة 30 ثانية، اتركيه 3 دقائق عند الحوض، ثم اشطفي. لا تضعيه على الجذور — الثقل عند الجذر يبدو دهنياً لا لامعاً.",
          keywords: ["بروتوكول","روتين","تطبيق","كيف","خدمة","ضغطات","حوض"] },
        { id: "price", title: "موضع السعر",
          content: "سعّري الخدمة لا العبوة. المنتج المنزلي يمدّ نتيجة الصالون بين المواعيد — وهذا هو سبب أخذه إلى المنزل.",
          keywords: ["سعر","تكلفة","قيمة","غالي","مقارنة"] },
      ],
      objections: [
        { objection: "عميلتي لن تدفع مقابل إضافة",
          keywords: ["غالي","سعر","تدفع","إضافة","بيع"],
          approvedResponse: "لا تبيعيها كإضافة — نفّذيها مرة عند الحوض ضمن الخدمة ودعيها ترى اللمعان في المرآة. حديث البيع يأتي بعد أن ترى النتيجة، لا قبلها." },
        { objection: "هل هو مثل علاج الكيراتين؟",
          keywords: ["كيراتين","علاج","دائم","فرد","تنعيم"],
          approvedResponse: "لا — هذا طقس لمعان يغلق طبقة الكيوتيكل، وليس خدمة فرد أو تنعيم. يمنح لمعاناً كالمرآة من الخدمة الأولى وهو آمن على الشعر المصبوغ." },
      ],
      doNotSay: ["لمعان دائم","يصلح الشعر نهائياً","مثل علاج الكيراتين"],
      approvedClaims: ["مركّب اللمعان الغليكوليبيدي","يغلق طبقة الكيوتيكل","يمنح لمعاناً كالمرآة من الخدمة الأولى","آمن على الشعر المصبوغ","استخدام احترافي: ضغطتان من المنتصف إلى الأطراف"],
    },
    ZH: {
      language: "ZH", status: "approved",
      sections: [
        { id: "positioning", title: "产品定位",
          content: "这首先是一项服务，其次才是零售产品。请在椅子上做定位：您在洗头台完成的光泽仪式，顾客回家后延续。",
          keywords: ["定位","介绍","是什么","产品","讲讲"] },
        { id: "claims", title: "核心宣称",
          content: "糖脂光泽复合物封闭毛鳞片，首次服务即带来镜面光泽。染后发质可安全使用。",
          keywords: ["宣称","功效","效果","光泽","证据"] },
        { id: "routine", title: "服务流程",
          content: "毛巾擦干后，中段至发尾取两泵，乳化30秒，在洗头台停留3分钟后冲洗。不要涂抹发根——发根有重量会显得油腻，而不是有光泽。",
          keywords: ["流程","protocol","怎么用","服务","泵","洗头台"] },
        { id: "price", title: "价格定位",
          content: "为服务定价，不是为瓶子定价。居家产品在两次预约之间延长沙龙效果——这才是带回家的理由。",
          keywords: ["价格","多少钱","价值","贵","对比"] },
      ],
      objections: [
        { objection: "我的顾客不会为加项买单",
          keywords: ["贵","价格","买单","加项","推销"],
          approvedResponse: "不要当作加项来卖——在服务中于洗头台做一次，让她在镜子里看到光泽。零售的对话发生在她看到效果之后，而不是之前。" },
        { objection: "这跟角蛋白护理一样吗？",
          keywords: ["角蛋白","护理","永久","拉直","顺滑"],
          approvedResponse: "不一样——这是封闭毛鳞片的光泽仪式，不是拉直或顺滑服务。首次服务即带来镜面光泽，染后发质也可安全使用。" },
      ],
      doNotSay: ["永久光泽","永久修复头发","等同角蛋白拉直"],
      approvedClaims: ["糖脂光泽复合物","封闭毛鳞片","首次服务即带来镜面光泽","染后发质可安全使用","专业用量：中段至发尾两泵"],
    },
    HI: {
      language: "HI", status: "approved",
      sections: [
        { id: "positioning", title: "पोज़िशनिंग",
          content: "यह पहले एक सर्विस है, बाद में रिटेल प्रोडक्ट। इसे कुर्सी पर रखिए: बेसिन पर किया जाने वाला शाइन रिचुअल, जिसे ग्राहक घर पर बनाए रखती हैं।",
          keywords: ["पोज़िशन","बताइए","क्या है","प्रोडक्ट","परिचय"] },
        { id: "claims", title: "मुख्य दावे",
          content: "ग्लाइकोलिपिड शाइन कॉम्प्लेक्स क्यूटिकल को सील करता है और पहली ही सर्विस से आईने जैसी चमक देता है। कलर किए बालों पर सुरक्षित।",
          keywords: ["दावा","नतीजे","चमक","सबूत"] },
        { id: "routine", title: "सर्विस प्रोटोकॉल",
          content: "तौलिये से सुखाए बालों पर मध्य से सिरों तक दो पंप, 30 सेकंड इमल्सिफ़ाई करें, बेसिन पर 3 मिनट छोड़ें, फिर धो लें। जड़ों पर न लगाएँ — जड़ पर भारीपन चमक नहीं, चिपचिपाहट दिखता है।",
          keywords: ["प्रोटोकॉल","रूटीन","कैसे","सर्विस","पंप","बेसिन"] },
        { id: "price", title: "कीमत की स्थिति",
          content: "बोतल की नहीं, सर्विस की कीमत रखें। घर का प्रोडक्ट दो अपॉइंटमेंट के बीच सैलून का नतीजा बनाए रखता है — घर ले जाने की वजह यही है।",
          keywords: ["कीमत","दाम","वैल्यू","महंगा","तुलना"] },
      ],
      objections: [
        { objection: "मेरी ग्राहक एड-ऑन के पैसे नहीं देंगी",
          keywords: ["महंगा","कीमत","पैसे","एड-ऑन","बेचना"],
          approvedResponse: "इसे एड-ऑन की तरह मत बेचिए — सर्विस के भीतर बेसिन पर एक बार कीजिए और उन्हें आईने में चमक देखने दीजिए। रिटेल की बात नतीजा देखने के बाद होती है, पहले नहीं।" },
        { objection: "क्या यह केराटिन ट्रीटमेंट जैसा है?",
          keywords: ["केराटिन","ट्रीटमेंट","स्थायी","स्ट्रेट","स्मूदनिंग"],
          approvedResponse: "नहीं — यह क्यूटिकल सील करने वाला शाइन रिचुअल है, स्ट्रेटनिंग या स्मूदनिंग सर्विस नहीं। पहली ही सर्विस से आईने जैसी चमक देता है और कलर किए बालों पर सुरक्षित है।" },
      ],
      doNotSay: ["स्थायी चमक","बाल हमेशा के लिए ठीक करता है","केराटिन ट्रीटमेंट जैसा"],
      approvedClaims: ["ग्लाइकोलिपिड शाइन कॉम्प्लेक्स","क्यूटिकल को सील करता है","पहली ही सर्विस से आईने जैसी चमक","कलर किए बालों पर सुरक्षित","प्रोफ़ेशनल मात्रा: मध्य से सिरों तक 2 पंप"],
    },
  },

  "maybelline-sky-high": {
    EN: {
      language: "EN", status: "source",
      sections: [
        { id: "positioning", title: "Positioning",
          content: "One line, said fast: limitless length and volume, no clumps. This is an impulse aisle purchase — lead with the result and the price point, not the technology.",
          keywords: ["positioning","message","about","what is","introduce"] },
        { id: "claims", title: "Hero claims (approved wording)",
          content: "Approved claims: flexible bristle brush for full lash coverage. Formula with bamboo extract and fibres. Delivers limitless length and volume. Washes off with warm water and cleanser.",
          keywords: ["claim","results","proof","works","bamboo","length","volume"] },
        { id: "routine", title: "How to use",
          content: "Wiggle the brush at the root and comb through to the tip. Two coats for volume. Remove with warm water and your normal cleanser.",
          keywords: ["routine","apply","use","how","steps","remove"] },
        { id: "price", title: "Price positioning",
          content: "Mass price point with a result shoppers associate with premium mascaras — that contrast is the whole pitch.",
          keywords: ["price","cost","cheap","value","compare"] },
        { id: "upsell", title: "Complete the look",
          content: "Add the micellar water for easy removal, or the brow pencil to finish the eye. Keep the add-on to one item at the till.",
          keywords: ["upsell","also","together","recommend","pair"] },
      ],
      objections: [
        { objection: "Does it smudge or flake?",
          keywords: ["smudge","flake","run","last","wear"],
          approvedResponse: "The formula is built to hold length through the day and washes off with warm water and your cleanser — no oil remover needed." },
      ],
      doNotSay: ["waterproof","lash growth","permanent","medical"],
      approvedClaims: ["flexible bristle brush","bamboo extract","limitless length and volume","washes off with warm water"],
    },
    HI: {
      language: "HI", status: "approved",
      sections: [
        { id: "positioning", title: "पोज़िशनिंग",
          content: "एक ही लाइन में, तेज़ी से: बेहिसाब लंबाई और वॉल्यूम, बिना क्लंप्स के। यह इम्पल्स खरीद है — टेक्नोलॉजी नहीं, नतीजा और कीमत सबसे पहले बताएं।",
          keywords: ["पोज़िशनिंग","संदेश","परिचय","क्या है","प्रोडक्ट"] },
        { id: "claims", title: "स्वीकृत दावे",
          content: "स्वीकृत दावे: पूरी लैश कवरेज के लिए फ्लेक्सिबल ब्रिसल ब्रश। बांस के अर्क और फाइबर वाला फॉर्मूला। बेहिसाब लंबाई और वॉल्यूम देता है। गुनगुने पानी और क्लेंज़र से आसानी से निकल जाता है।",
          keywords: ["दावा","नतीजा","असर","बांस","लंबाई","वॉल्यूम"] },
        { id: "routine", title: "इस्तेमाल कैसे करें",
          content: "ब्रश को जड़ों पर हिलाते हुए लगाएं और सिरे तक कंघी करें। वॉल्यूम के लिए दो कोट। गुनगुने पानी और सामान्य क्लेंज़र से हटाएं।",
          keywords: ["रूटीन","लगाना","कैसे","इस्तेमाल","हटाना"] },
        { id: "price", title: "कीमत की बात",
          content: "मास कीमत पर वह नतीजा जो ग्राहक प्रीमियम मस्कारा से जोड़ते हैं — यही पूरा पिच है।",
          keywords: ["कीमत","महंगा","सस्ता","तुलना"] },
      ],
      objections: [
        { objection: "क्या यह फैलता या झड़ता है?",
          keywords: ["फैलता","झड़ता","टिकता","चलता"],
          approvedResponse: "यह फॉर्मूला दिन भर लंबाई बनाए रखने के लिए बना है और गुनगुने पानी तथा आपके क्लेंज़र से निकल जाता है — किसी ऑयल रिमूवर की ज़रूरत नहीं।" },
      ],
      doNotSay: ["वॉटरप्रूफ","लैश ग्रोथ","स्थायी","मेडिकल"],
      approvedClaims: ["फ्लेक्सिबल ब्रिसल ब्रश","बांस के अर्क","बेहिसाब लंबाई और वॉल्यूम","गुनगुने पानी से निकल जाता है"],
    },
    AR: {
      language: "AR", status: "approved",
      sections: [
        { id: "positioning", title: "الموضع التسويقي",
          content: "الرسالة كاملة في سطر: النتيجة التي تربطها العميلة بالماسكارا الفاخرة، بسعر متاح. أمامكِ ثوانٍ عند الرفّ — كوني سريعة.",
          keywords: ["تقديم","الرسالة","ما هو","عرّفي","المنتج"] },
        { id: "claims", title: "الادعاءات المعتمدة",
          content: "خلاصة الخيزران والألياف تمنح طولاً بلا حدود. الفرشاة المرنة تصل إلى كل رمش دون تكتّل. تُزال بالماء الدافئ.",
          keywords: ["ادعاء","نتائج","طول","خيزران","فعالية"] },
        { id: "routine", title: "العرض عند الرفّ",
          content: "حرّكي الفرشاة عند الجذور ثم اسحبيها إلى الأطراف، وضعي الطبقة الثانية والأولى ما زالت رطبة. عشر ثوانٍ من التجربة على ظهر اليد تُقنع أكثر من أي كلام.",
          keywords: ["روتين","استخدام","كيف","عرض","فرشاة"] },
        { id: "price", title: "موضع السعر",
          content: "سعر متاح مقابل النتيجة التي تربطها العميلة بالماسكارا الفاخرة — وهذه هي الرسالة كاملة.",
          keywords: ["سعر","تكلفة","قيمة","غالي","مقارنة"] },
      ],
      objections: [
        { objection: "الماسكارا الرخيصة تتلطّخ",
          keywords: ["تتلطخ","رخيص","تتساقط","جودة"],
          approvedResponse: "هذه تُزال بالماء الدافئ دون الحاجة لمزيل، والتركيبة تمنح طولاً دون تكتّل. دعيني أجرّبها على ظهر يدكِ — عشر ثوانٍ وسترين." },
        { objection: "أستخدم ماركة فاخرة",
          keywords: ["فاخرة","ماركة","غالي","أصلاً"],
          approvedResponse: "إذاً أنتِ تعرفين شكل الطول الجيد. هذه تمنح طولاً بلا حدود بفرشاة مرنة تصل إلى كل رمش، بسعر متاح. تمنحينني عشر ثوانٍ؟" },
      ],
      doNotSay: ["ينمّي الرموش","تأثير إطالة دائم","مُختبر طبياً"],
      approvedClaims: ["خلاصة الخيزران والألياف","طول بلا حدود","فرشاة مرنة تصل إلى كل رمش","لا تتكتّل","تُزال بالماء الدافئ"],
    },
    FR: {
      language: "FR", status: "approved",
      sections: [
        { id: "positioning", title: "Positionnement",
          content: "Tout le pitch en une phrase : le résultat que les clientes associent à un mascara premium, à un prix grand public. La vitesse compte — vous avez quelques secondes en rayon.",
          keywords: ["positionnement","message","présenter","c'est quoi","produit","parlez"] },
        { id: "claims", title: "Allégations approuvées",
          content: "L'extrait de bambou et les fibres construisent une longueur sans limite. La brosse flexible atteint chaque cil sans faire de paquets. Se retire à l'eau tiède.",
          keywords: ["allégation","résultats","longueur","bambou","preuve"] },
        { id: "routine", title: "Démo en rayon",
          content: "Zigzag à la racine, balayage vers la pointe, seconde couche pendant que la première est encore humide. Dix secondes de démonstration sur le dos de la main convertissent mieux que n'importe quelle allégation.",
          keywords: ["routine","appliquer","utiliser","comment","démo","brosse"] },
        { id: "price", title: "Positionnement prix",
          content: "Un prix grand public pour le résultat que les clientes associent au mascara premium — c'est tout le pitch.",
          keywords: ["prix","coût","valeur","cher","comparer"] },
      ],
      objections: [
        { objection: " Les mascaras pas chers coulent ",
          keywords: ["coule","pas cher","bon marché","qualité","tient"],
          approvedResponse: "Celui-ci se retire à l'eau tiède, sans démaquillant, et la formule construit la longueur sans paquets. Laissez-moi vous le montrer sur le dos de la main — dix secondes et vous verrez." },
        { objection: " J'achète une marque premium ",
          keywords: ["premium","marque","luxe","déjà","cher"],
          approvedResponse: "Alors vous savez déjà à quoi ressemble une belle longueur. Celui-ci donne une longueur sans limite avec une brosse flexible qui atteint chaque cil, à prix grand public. Dix secondes sur le dos de la main ?" },
      ],
      doNotSay: ["fait pousser les cils","effet extension permanent","testé médicalement"],
      approvedClaims: ["extrait de bambou et fibres","longueur sans limite","brosse flexible qui atteint chaque cil","sans paquets","se retire à l'eau tiède"],
    },
    ZH: {
      language: "ZH", status: "approved",
      sections: [
        { id: "positioning", title: "产品定位",
          content: "一句话讲完：顾客心中高端睫毛膏才有的效果，用大众价格实现。速度很重要——在货架前您只有几秒钟。",
          keywords: ["定位","介绍","是什么","产品","讲讲"] },
        { id: "claims", title: "核心宣称",
          content: "竹提取物与纤维打造无限长度。柔韧刷头触及每一根睫毛且不结块。温水即可卸除。",
          keywords: ["宣称","功效","长度","竹","证据"] },
        { id: "routine", title: "货架演示",
          content: "根部轻轻摆动，向睫毛尖端刷开，第一层未干时叠加第二层。在手背上做十秒演示，比任何宣称都更能促成购买。",
          keywords: ["流程","怎么用","使用","演示","刷头"] },
        { id: "price", title: "价格定位",
          content: "用大众价格换来顾客心中高端睫毛膏的效果——这就是全部卖点。",
          keywords: ["价格","多少钱","价值","贵","对比"] },
      ],
      objections: [
        { objection: "便宜的睫毛膏会晕",
          keywords: ["晕","便宜","掉","质量","脱妆"],
          approvedResponse: "这支用温水就能卸除，不需要卸妆油，配方拉长且不结块。我在您手背上演示一下——十秒钟您就看到了。" },
        { objection: "我用高端品牌",
          keywords: ["高端","品牌","贵","奢侈","已经"],
          approvedResponse: "那您已经知道好的长度是什么样。这支用柔韧刷头触及每一根睫毛，打造无限长度，价格却很亲民。愿意给我十秒钟吗？" },
      ],
      doNotSay: ["促进睫毛生长","永久接睫效果","经医学测试"],
      approvedClaims: ["竹提取物与纤维","打造无限长度","柔韧刷头触及每一根睫毛","不结块","温水即可卸除"],
    },
    JA: {
      language: "JA", status: "approved",
      sections: [
        { id: "positioning", title: "ポジショニング",
          content: "一言でいえば：お客様がプレステージのマスカラに期待する仕上がりを、手に取りやすい価格で。棚の前では数秒が勝負ですので、短くお伝えください。",
          keywords: ["紹介","メッセージ","どんな","製品","説明"] },
        { id: "claims", title: "承認訴求",
          content: "竹エキスとファイバーが限りない長さを重ねます。しなやかなブラシが一本一本に届き、ダマになりにくい仕上がり。ぬるま湯でオフできます。",
          keywords: ["訴求","効果","長さ","竹","証拠"] },
        { id: "routine", title: "店頭デモ",
          content: "根元で小刻みに動かし、毛先へ向かって流します。1度目が乾かないうちに2度目を重ねてください。手の甲での10秒のデモは、どんな説明よりも伝わります。",
          keywords: ["手順","使い方","デモ","ブラシ","塗り方"] },
        { id: "price", title: "価格ポジション",
          content: "プレステージのマスカラに期待される仕上がりを、手に取りやすい価格で——お伝えすることはこれだけです。",
          keywords: ["価格","値段","高い","価値","比較"] },
      ],
      objections: [
        { objection: "安いマスカラはにじみますよね",
          keywords: ["にじむ","安い","落ちる","品質","パンダ"],
          approvedResponse: "こちらはリムーバーを使わずぬるま湯でオフでき、処方はダマにならずに長さを出します。手の甲でお試しいただけますか——10秒でお分かりいただけます。" },
        { objection: "プレステージブランドを使っています",
          keywords: ["プレステージ","ブランド","高級","もう","デパート"],
          approvedResponse: "でしたら良い長さがどういうものかご存じですね。こちらはしなやかなブラシで一本一本に届き、限りない長さを、手に取りやすい価格で。10秒だけいただけますか。" },
      ],
      doNotSay: ["まつげが伸びる","エクステの永久的な効果","医学的に試験済み"],
      approvedClaims: ["竹エキスとファイバー配合","限りない長さを重ねられます","しなやかなブラシが一本一本に届きます","ダマになりにくい","ぬるま湯でオフできます"],
    },
  },
};
