export const GEO: Record<string, string[]> = {
  Selangor: [
    "Petaling",
    "Klang",
    "Hulu Langat",
    "Gombak",
    "Sepang",
    "Kuala Langat",
    "Kuala Selangor",
    "Hulu Selangor",
    "Sabak Bernam",
  ],
  "Kuala Lumpur": ["Kuala Lumpur"],
  Johor: [
    "Johor Bahru",
    "Batu Pahat",
    "Kluang",
    "Muar",
    "Kulai",
    "Segamat",
    "Pontian",
    "Kota Tinggi",
    "Mersing",
    "Tangkak",
  ],
  "Pulau Pinang": [
    "Timur Laut",
    "Barat Daya",
    "SP Utara",
    "SP Tengah",
    "SP Selatan",
  ],
  Perak: [
    "Kinta",
    "Larut Matang",
    "Manjung",
    "Hilir Perak",
    "Kerian",
    "Kuala Kangsar",
    "Batang Padang",
  ],
  Sabah: [
    "Kota Kinabalu",
    "Sandakan",
    "Tawau",
    "Penampang",
    "Lahad Datu",
    "Keningau",
    "Lain-lain",
  ],
  Sarawak: ["Kuching", "Miri", "Sibu", "Bintulu", "Samarahan", "Lain-lain"],
  Kedah: [
    "Kota Setar",
    "Kuala Muda",
    "Kulim",
    "Kubang Pasu",
    "Langkawi",
    "Lain-lain",
  ],
  Kelantan: ["Kota Bharu", "Pasir Mas", "Tumpat", "Bachok", "Lain-lain"],
  Terengganu: [
    "Kuala Terengganu",
    "Kemaman",
    "Dungun",
    "Besut",
    "Lain-lain",
  ],
  Pahang: [
    "Kuantan",
    "Temerloh",
    "Bentong",
    "Cameron Highlands",
    "Lain-lain",
  ],
  "Negeri Sembilan": ["Seremban", "Port Dickson", "Jempol", "Lain-lain"],
  Melaka: ["Melaka Tengah", "Alor Gajah", "Jasin"],
  Perlis: ["Kangar", "Arau"],
  Putrajaya: ["Putrajaya"],
  Labuan: ["Labuan"],
};

export const STATES = Object.keys(GEO);
